# Generated by Django 3.2.4 on 2021-06-16 00:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estatura', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
            managers=[
                ('pacientes', django.db.models.manager.Manager()),
            ],
        ),
    ]
